INSERT INTO items (item_name, is_contributable)
VALUES
('Radiation Suit Mk4', FALSE),
('Radiation Suit Mk5', FALSE),
('Radiation Suit Mk6', FALSE),
('Caladan Casual Trousers', FALSE),
('Caladan Casual Boots', FALSE),
('Caladan Casual Tunic', FALSE),
('Maula Breeches', FALSE),
('Maula Bracers', FALSE),
('Maula Boots', FALSE),
('Maula Tunic', FALSE),
('Maula Vest', FALSE),
('Giedi Casual Shoes', FALSE),
('Giedi Casual Pants', FALSE),
('Giedi Casual Shirt', FALSE),
('Entrepreneur Casual Shoes', FALSE),
('Entrepreneur Casual Pants', FALSE),
('Entrepreneur Casual Gloves', FALSE),
('Entrepreneur Casual Shirt', FALSE),
('Slaver Stillsuit Boots', FALSE),
('Slaver Stillsuit Gloves', FALSE),
('Slaver Stillsuit Mask', FALSE),
('Slaver Stillsuit Body', FALSE),
('Kirab Stillsuit Boots', FALSE),
('Kirab Stillsuit Gloves', FALSE),
('Kirab Stillsuit Mask', FALSE),
('Kirab Stillsuit Body', FALSE),
('Native Stillsuit Boots', FALSE),
('Native Stillsuit Gloves', FALSE),
('Native Stillsuit Mask', FALSE),
('Native Stillsuit Body', FALSE),
('Mercenary Stillsuit Boots', FALSE),
('Mercenary Stillsuit Gloves', FALSE),
('Mercenary Stillsuit Mask', FALSE),
('Mercenary Stillsuit Body', FALSE),
('CHOAM Stillsuit Boots', FALSE),
('CHOAM Stillsuit Gloves', FALSE),
('CHOAM Stillsuit Mask', FALSE),
('CHOAM Stillsuit Body', FALSE),
('Scavenger Stillsuit Boots', FALSE),
('Scavenger Stillsuit Gloves', FALSE),
('Scavenger Stillsuit Mask', FALSE),
('Scavenger Stillsuit Body', FALSE),
('Hollower Stillsuit Garment', FALSE),
('The Jackal''s Blindfold', FALSE),
('Arrakeen Palace Servant�s Trousers', FALSE),
('Arrakeen Palace Servant�s Shoes', FALSE),
('Duneman Heavy Boots', FALSE),
('Kirab Heavy Boots', FALSE),
('Slaver Heavy Boots', FALSE),
('Mercenary Heavy Boots', FALSE),
('CHOAM Heavy Boots', FALSE),
('Duneman Heavy Gloves', FALSE),
('Kirab Heavy Gauntlet', FALSE),
('Slaver Heavy Gloves', FALSE),
('Mercenary Heavy Gloves', FALSE),
('CHOAM Heavy Gauntlets', FALSE),
('Duneman Heavy Mask', FALSE),
('Kirab Heavy Headwrap', FALSE),
('Slaver Heavy Helmet', FALSE),
('Mercenary Heavy Helmet', FALSE),
('CHOAM Heavy Helmet', FALSE),
('Duneman Heavy Pants', FALSE),
('Kirab Heavy Pants', FALSE),
('Slaver Heavy Pants', FALSE),
('Mercenary Heavy Pants', FALSE),
('CHOAM Heavy Greaves', FALSE),
('Duneman Heavy Jacket', FALSE),
('Kirab Heavy Jerkin', FALSE),
('Slaver Heavy Jerkin', FALSE),
('Mercenary Heavy Chestplate', FALSE),
('CHOAM Heavy Chestplate', FALSE),
('Kirab Scout Boots', FALSE),
('Slaver Scout Boots', FALSE),
('Mercenary Scout Boots', FALSE),
('CHOAM Scout Boots', FALSE),
('Duneman Scout Boots', FALSE),
('Syndicate Boots', FALSE),
('The Forge Boots', FALSE),
('Makeshift Shoes', FALSE),
('Scavenger Boots', FALSE),
('Aren''s Boots', FALSE),
('Mendia''s Boots', FALSE),
('Inkvine Boots', FALSE),
('Quirth''s Boots', FALSE),
('Chosen Boots', FALSE),
('Pincushion Boots', FALSE),
('Kirab Scout Gloves', FALSE),
('Slaver Scout Gloves', FALSE),
('Mercenary Scout Gloves', FALSE),
('CHOAM Scout Gloves', FALSE),
('Duneman Scout Gloves', FALSE),
('Syndicate Gauntlets', FALSE),
('The Forge Gloves', FALSE),
('Makeshift Gloves', FALSE),
('Scavenger Gloves', FALSE),
('Aren''s Gloves', FALSE),
('Mendia''s Gauntlets', FALSE),
('Inkvine Gauntlets', FALSE),
('Quirth''s Gauntlets', FALSE),
('Chosen Gauntlets', FALSE),
('Pincushion Gauntlets', FALSE),
('Kirab Scout Helmet', FALSE),
('Slaver Scout Mask', FALSE),
('Mercenary Scout Helmet', FALSE),
('CHOAM Scout Helmet', FALSE),
('Duneman Scout Helmet', FALSE),
('Syndicate Helmet', FALSE),
('The Forge Helmet', FALSE),
('Makeshift Hood', FALSE),
('Scavenger Hood', FALSE),
('Aren''s Mask', FALSE),
('Mendia''s Wrap', FALSE),
('Inkvine Mask', FALSE),
('Quirth''s Helmet', FALSE),
('Chosen Helmet', FALSE),
('Pincushion Helmet', FALSE),
('Phaedra''s Mask', FALSE),
('Atreides Heavy Pants', FALSE),
('Kirab Scout Pants', FALSE),
('Slaver Scout Pants', FALSE),
('Mercenary Scout Leggings', FALSE),
('CHOAM Scout Pants', FALSE),
('Duneman Scout Pants', FALSE),
('Syndicate Pants', FALSE),
('The Forge Pants', FALSE),
('Makeshift Pants', FALSE),
('Scavenger Pants', FALSE),
('Aren''s Pants', FALSE),
('Mendia''s Pants', FALSE),
('Inkvine Pants', FALSE),
('Quirth''s Pants', FALSE),
('Chosen Pants', FALSE),
('Pincushion Pants', FALSE),
('Atreides Heavy Chestpiece', FALSE),
('Kirab Scout Jacket', FALSE),
('Slaver Scout Jacket', FALSE),
('Mercenary Scout Top', FALSE),
('CHOAM Scout Chestplate', FALSE),
('Duneman Scout Jacket', FALSE),
('Syndicate Chestplate', FALSE),
('The Forge Chestpiece', FALSE),
('Harkonnen Scout Chestpiece', FALSE),
('Skin-lined Jacket', FALSE),
('Miner''s Blessing', FALSE),
('Station Garb', FALSE),
('Desert Garb', FALSE),
('Makeshift Jacket', FALSE),
('Scavenger Chestpiece', FALSE),
('Aren''s Chestpiece', FALSE),
('Mendia''s Jacket', FALSE),
('Inkvine Jacket', FALSE),
('Quirth''s Jacket', FALSE),
('Chosen Chestplate', FALSE),
('Pincushion Chestpiece', FALSE),
('Oathbreaker Boots', FALSE),
('Karak''s Boots', FALSE),
('Sentinel Boots', FALSE),
('Acheronian Boots', FALSE),
('Executor''s Boots', FALSE),
('Oathbreaker Gauntlets', FALSE),
('Karak''s Gauntlets', FALSE),
('Sentinel Gauntlets', FALSE),
('Acheronian Gauntlets', FALSE),
('Executor''s Gauntlets', FALSE),
('Oathbreaker Headwrap', FALSE),
('Karak''s Helmet', FALSE),
('Sentinel Helmet', FALSE),
('Acheronian Helmet', FALSE),
('Executor''s Helmet', FALSE),
('Oathbreaker Pants', FALSE),
('Karak''s Pants', FALSE),
('Sentinel Pants', FALSE),
('Acheronian Pants', FALSE),
('Executor''s Pants', FALSE),
('Oathbreaker Chestpiece', FALSE),
('Karak''s Jacket', FALSE),
('Sentinel Jacket', FALSE),
('Acheronian Chestplate', FALSE),
('Executor''s Chestpiece', FALSE),
('Mendek''s Boots', FALSE),
('Bulwark Boots', FALSE),
('Mendek''s Gauntlets', FALSE),
('Bulwark Gloves', FALSE),
('Mendek''s Helmet', FALSE),
('Bulwark Helmet', FALSE),
('Mendek''s Pants', FALSE),
('Bulwark Leggings', FALSE),
('Mendek''s Chestplate', FALSE),
('Bulwark Chest', FALSE),
('Hook-claw Gloves', FALSE),
('Reaper Gloves', FALSE),
('Improved Reaper Gloves', FALSE),
('Advanced Reaper Gloves', FALSE),
('Yueh''s Reaper Gloves', FALSE),
('Iri''s Gauntlets', FALSE),
('Shock Gauntlets', FALSE),
('Power Gauntlets', FALSE),
('Station Gauntlets', FALSE),
('Circuit Gauntlets', FALSE),
('Power Harness', FALSE),
('Wayfinder Helm', FALSE),
('Wayfinder Helm', FALSE),
('Compression-Stim Leggings', FALSE),
('Stim-Leggings ', FALSE),
('Ix-core Leggings', FALSE),
('Desert Dasher Garment', FALSE),
('Sprinter''s Stillsuit Garment', FALSE),
('Sand Strider Stillsuit Garment', FALSE),
('Maraqeb Stillsuit Boots', FALSE),
('Maraqeb Stillsuit Gloves', FALSE),
('Maraqeb Stillsuit Mask', FALSE),
('Maraqeb Stillsuit Garment', FALSE),
('Batigh Stillsuit Boots', FALSE),
('Batigh Stillsuit Gloves', FALSE),
('Batigh Stillsuit Mask', FALSE),
('Batigh Stillsuit Garment', FALSE),
('Villari''s Stillsuit Boots', FALSE),
('Villari''s Stillsuit Gloves', FALSE),
('Villari''s Stillsuit Mask', FALSE),
('Villari''s Stillsuit Garment', FALSE),
('Shadow Hood', FALSE),
('Shaded Hood', FALSE),
('Pardot''s Hood', FALSE),
('Rigged Suspensor Jacket', FALSE),
('Improved Suspensor Jacket', FALSE),
('Advanced Suspensor Jacket', FALSE),
('Idaho''s Charge', FALSE),
('Boots of the Sisterhood', FALSE),
('Gloves of the Sisterhood', FALSE),
('Veil of the Sisterhood', FALSE),
('Leggings of the Sisterhood', FALSE),
('Robe of the Sisterhood', FALSE),
('Reinforced Boots of the Mentat', FALSE),
('Gauntlets of the Mentat', FALSE),
('Helm of the Mentat', FALSE),
('Leggings of the Mentat', FALSE),
('Tactical Coat of the Mentat', FALSE),
('Planetologist Light Armor Boots', FALSE),
('Planetologist Light Armor Gloves', FALSE),
('Planetologist Light Armor Headpiece', FALSE),
('Planetologist Light Armor Leggings', FALSE),
('Planetologist Light Armor Coat', FALSE),
('Boots of Ginaz', FALSE),
('Gauntlets of Ginaz', FALSE),
('Helm of Ginaz', FALSE),
('Leggings of Ginaz', FALSE),
('Tunic of Ginaz', FALSE),
('Trooper Heavy Armor Tactical Boots', FALSE),
('Trooper Heavy Armor Tactical Gauntlets', FALSE),
('Trooper Heavy Armor Tactical Helmet', FALSE),
('Trooper Heavy Armor Tactical Pants', FALSE),
('Trooper Heavy Armor Tactical Coat', FALSE),
('Softstep Boots', FALSE),
('Ta''lab Softstep Boots', FALSE),
('Idaho Softstep Boots', FALSE),
('Tarl Softstep Boots', FALSE),
('Tabr Softstep Boots', FALSE),
('Spice Mask', FALSE),
('Hollower Stillsuit Boots', FALSE),
('Hollower Stillsuit Gloves', FALSE),
('Hollower Stillsuit Mask', FALSE),
('Menol''s Stillsuit Boots', FALSE),
('Menol''s Stillsuit Gloves', FALSE),
('Menol''s Stillsuit Mask', FALSE),
('Menol''s Stillsuit Garment', FALSE),
('Kel''s Stillsuit Boots', FALSE),
('Kel''s Stillsuit Gloves', FALSE),
('Kel''s Stillsuit Mask', FALSE),
('Kel''s Stillsuit Garment', FALSE),
('Shadrath''s Stillsuit Boots', FALSE),
('Shadrath''s Stillsuit Gloves', FALSE),
('Shadrath''s Stillsuit Mask', FALSE),
('Shadrath''s Stillsuit Garment', FALSE),
('Saturnine Stillsuit Boots', FALSE),
('Saturnine Stillsuit Gloves', FALSE),
('Saturnine Stillsuit Mask', FALSE),
('Saturnine Stillsuit Garment', FALSE),
('Imperial Stillsuit Boots', FALSE),
('Imperial Stillsuit Gloves', FALSE),
('Imperial Stillsuit Mask', FALSE),
('Shaddam''s Bladder', FALSE),
('Imperial Stillsuit Garment', FALSE),
('Imperial Casual Top', FALSE),
('Imperial Casual Shoes', FALSE),
('Dune Dancer Stillsuit Garment', FALSE),
('Crew Chief�s Stillsuit Garment', FALSE),
('Tactical Radiation Suit', FALSE),
('Arrakeen Palace Servant�s Tunic', FALSE),
('Literjon', FALSE),
('Healkit', FALSE),
('Melange Spiced Food', FALSE),
('Melange Spiced Beer', FALSE),
('Melange Spiced Coffee', FALSE),
('Melange Spiced Wine', FALSE),
('Hajra Literjon Mk1', FALSE),
('Iodine Pill', FALSE),
('Cup of Water', FALSE),
('Sapho Juice', FALSE),
('Small Blood Sack', FALSE),
('Decaliterjon', FALSE),
('Healkit Mk2', FALSE),
('Healkit Mk4', FALSE),
('Medium Blood Sack', FALSE),
('Large Blood Sack', FALSE),
('Mouse Corpse', FALSE),
('Melange Spiced Liquor', FALSE),
('Literjon Mk6', FALSE),
('Massive Blood Sack', FALSE),
('Healkit Mk6', FALSE),
('Hajra Literjon Mk2', FALSE),
('Hajra Literjon Mk3', FALSE),
('Hajra Literjon Mk4', FALSE),
('Hajra Literjon Mk5', FALSE),
('Hajra Literjon Mk6', FALSE),
('Scipio''s Bloodbag', FALSE),
('Glutton''s Bloodbag', FALSE),
('Sinner''s Bloodbag', FALSE),
('Maas Kharet Bloodbag', FALSE),
('The Baron''s Bloodbag', FALSE),
('Experimental Toxin-Absorption Pills', FALSE),
('Respawn Beacon', FALSE),
('Stilltent', FALSE),
('Thumper', FALSE),
('Clapper Mk4', FALSE),
('Double-sealed Stilltent', FALSE),
('Aluminum Ingot', TRUE),
('Copper Ore', TRUE),
('Aluminum Ore', TRUE),
('Copper Ingot', TRUE),
('Carbon Ore', TRUE),
('Flour Sand', TRUE),
('Small Vehicle Fuel Cell', TRUE),
('Iron Ingot', TRUE),
('Medium Sized Vehicle Fuel Cell', TRUE),
('Large Vehicle Fuel Cell', TRUE),
('Iron Ore', TRUE),
('On Witches', FALSE),
('Plant Fiber', TRUE),
('Salvaged Metal', TRUE),
('Silicone Block', TRUE),
('Solari', TRUE),
('Spice Melange', TRUE),
('Spice Sand', TRUE),
('Granite Stone', TRUE),
('Welding Wire', TRUE),
('Jasmium Crystal', TRUE),
('Basalt Stone', TRUE),
('Steel Ingot', TRUE),
('Duraluminum Ingot', TRUE),
('Erythrite Crystal', TRUE),
('Cobalt Paste', TRUE),
('Spice Residue', TRUE),
('Agave Seeds', TRUE),
('EMF Generator', TRUE),
('Micro-sandwich Fabric', TRUE),
('Advanced Servoks', TRUE),
('Particle Capacitor', TRUE),
('Plasteel Microflora Fiber', TRUE),
('Mechanical Parts', TRUE),
('Corpse', TRUE),
('Plastone', TRUE),
('Titanium Ore', TRUE),
('Stravidium Mass', TRUE),
('Armor Plating', TRUE),
('Blade Parts', TRUE),
('Gun Parts', TRUE),
('Range Finder', TRUE),
('Complex Machinery', TRUE),
('Holtzman Actuator', TRUE),
('Calibrated Servok', TRUE),
('Ray Amplifier', TRUE),
('Irradiated Slag', TRUE),
('Industrial Pump', TRUE),
('Heavy Caliber Compressor', TRUE),
('Light Caliber Compressor', TRUE),
('Insulated Fabric', TRUE),
('Diamondine Dust', TRUE),
('Carbide Scraps', TRUE),
('Sandtrout Leathers', TRUE),
('Stillsuit Tubing', TRUE),
('Off-world Medical Supplies', TRUE),
('Spice-infused Copper Dust', TRUE),
('Spice-infused Iron Dust', TRUE),
('Spice-infused Steel Dust', TRUE),
('Spice-infused Aluminum Dust', TRUE),
('Spice-infused Duraluminum Dust', TRUE),
('Spice-infused Plastanium Dust', TRUE),
('Plastanium Ingot', TRUE),
('Stravidium Fiber', TRUE),
('Low-grade Lubricant', TRUE),
('Industrial-grade Lubricant', TRUE),
('Makeshift Filter', TRUE),
('Standard Filter', TRUE),
('Particulate Filter', TRUE),
('Advanced Particulate Filter', TRUE),
('Spice-infused Fuel Cell', TRUE),
('Military Power Regulator', TRUE),
('Hydraulic Piston', TRUE),
('Thermoelectric Cooler', TRUE),
('Blank Sinkchart', FALSE),
('Plasteel Composite Armor Plating', TRUE),
('Plasteel Composite Blade Parts', TRUE),
('Plasteel Composite Gun Parts', TRUE),
('Improved Holtzman Actuator', TRUE),
('Precision Range Finder', TRUE),
('Advanced Machinery', TRUE),
('Thermo-Responsive Ray Amplifier', TRUE),
('Irradiated Core', TRUE),
('Fluid Efficient Industrial Pump', TRUE),
('Fluted Heavy Caliber Compressor', TRUE),
('Fluted Light Caliber Compressor', TRUE),
('Atmospheric Filtered Fabric', TRUE),
('Diamodine blade parts', TRUE),
('Carbide blade parts', TRUE),
('Ballistic Weave Fabric', TRUE),
('Improved Watertube', TRUE),
('Overclocked Power Regulator', TRUE),
('Tri-Forged Hydraulic Piston', TRUE),
('Plasteel Plate', TRUE),
('Worm Tooth', FALSE),
('Opafire Gem', TRUE),
('Ship Manifest', FALSE),
('Offworld Regis Compound', TRUE),
('Regis Component', TRUE),
('Schematic Pattern Grade 1', TRUE),
('Schematic Pattern Grade 2', TRUE),
('Schematic Pattern Grade 3', TRUE),
('Schematic Pattern Grade 4', TRUE),
('Schematic Pattern Grade 5', TRUE),
('Damasteel Sword', FALSE),
('Experimental Power Pack Component', FALSE),
('Surveillance Sensor Schematic', FALSE),
('Experimental Wind Turbine Schematic', FALSE),
('Sealed Recorder Schematic', FALSE),
('Ixian Transeye Schematic', FALSE),
('Buggy Booster Mk3', FALSE),
('Buggy Booster Mk4', FALSE),
('Buggy Booster Mk5', FALSE),
('Buggy Booster Mk6', FALSE),
('Rattler Boost Module Mk3', FALSE),
('Rattler Boost Module Mk4', FALSE),
('Rattler Boost Module Mk5', FALSE),
('Rattler Boost Module Mk6', FALSE),
('Buggy Chassis Mk3', FALSE),
('Buggy Chassis Mk4', FALSE),
('Buggy Chassis Mk5', FALSE),
('Buggy Chassis Mk6', FALSE),
('Buggy Engine Mk3', FALSE),
('Buggy Engine Mk4', FALSE),
('Buggy Engine Mk5', FALSE),
('Buggy Engine Mk6', FALSE),
('Bluddshot Buggy Engine Mk3', FALSE),
('Bluddshot Buggy Engine Mk4', FALSE),
('Bluddshot Buggy Engine Mk5', FALSE),
('Bluddshot Buggy Engine Mk6', FALSE),
('Buggy PSU Mk3', FALSE),
('Buggy PSU Mk4', FALSE),
('Buggy PSU Mk5', FALSE),
('Buggy PSU Mk6', FALSE),
('Buggy Rear Mk3', FALSE),
('Buggy Rear Mk4', FALSE),
('Buggy Rear Mk5', FALSE),
('Buggy Rear Mk6', FALSE),
('Buggy Utility Rear Mk3', FALSE),
('Buggy Utility Rear Mk4', FALSE),
('Buggy Utility Rear Mk5', FALSE),
('Buggy Utility Rear Mk6', FALSE),
('Buggy Hull Mk3', FALSE),
('Buggy Hull Mk4', FALSE),
('Buggy Hull Mk5', FALSE),
('Buggy Hull Mk6', FALSE),
('Buggy Storage Mk3', FALSE),
('Buggy Storage Mk4', FALSE),
('Buggy Storage Mk5', FALSE),
('Buggy Storage Mk6', FALSE),
('Bigger Buggy Boot Mk3', FALSE),
('Bigger Buggy Boot Mk4', FALSE),
('Bigger Buggy Boot Mk5', FALSE),
('Bigger Buggy Boot Mk6', FALSE),
('Buggy Rocket Launcher Mk5', FALSE),
('Rocket', FALSE),
('Buggy Rocket Launcher Mk6', FALSE),
('Buggy Tread Mk3', FALSE),
('Buggy Tread Mk4', FALSE),
('Buggy Tread Mk5', FALSE),
('Buggy Tread Mk6', FALSE),
('Buggy Cutteray Mk3', FALSE),
('Buggy Cutteray Mk4', FALSE),
('Buggy Cutteray Mk5', FALSE),
('Buggy Cutteray Mk6', FALSE),
('Focused Buggy Cutteray Mk3', FALSE),
('Focused Buggy Cutteray Mk4', FALSE),
('Focused Buggy Cutteray Mk5', FALSE),
('Focused Buggy Cutteray Mk6', FALSE),
('Scout Ornithopter Thruster Mk4', FALSE),
('Scout Ornithopter Thruster Mk5', FALSE),
('Scout Ornithopter Thruster Mk6', FALSE),
('Stormrider Boost Module Mk4', FALSE),
('Stormrider Boost Module Mk5', FALSE),
('Stormrider Boost Module Mk6', FALSE),
('Scout Ornithopter Chassis Mk4', FALSE),
('Scout Ornithopter Chassis Mk5', FALSE),
('Scout Ornithopter Chassis Mk6', FALSE),
('Scout Ornithopter Engine Mk4', FALSE),
('Scout Ornithopter Engine Mk5', FALSE),
('Scout Ornithopter Engine Mk6', FALSE),
('Scout Ornithopter Generator Mk4', FALSE),
('Scout Ornithopter Generator Mk5', FALSE),
('Scout Ornithopter Generator Mk6', FALSE),
('Scout Ornithopter Hull Mk4', FALSE),
('Scout Ornithopter Hull Mk5', FALSE),
('Scout Ornithopter Hull Mk6', FALSE),
('Scout Ornithopter Cockpit Mk4', FALSE),
('Scout Ornithopter Cockpit Mk5', FALSE),
('Scout Ornithopter Cockpit Mk6', FALSE),
('Scout Ornithopter Storage Mk4', FALSE),
('Scout Ornithopter Rocket Launcher Mk5', FALSE),
('Scout Ornithopter Rocket Launcher Mk6', FALSE),
('Scout Ornithopter Wing Mk4', FALSE),
('Scout Ornithopter Wing Mk5', FALSE),
('Scout Ornithopter Wing Mk6', FALSE),
('Albatross Wing Module Mk4', FALSE),
('Albatross Wing Module Mk5', FALSE),
('Albatross Wing Module Mk6', FALSE),
('Scout Ornithopter Scan Module', FALSE),
('Assault Ornithopter Thruster Mk5', FALSE),
('Assault Ornithopter Thruster Mk6', FALSE),
('Steady Assault Boost Module Mk5', FALSE),
('Steady Assault Boost Module Mk6', FALSE),
('Assault Ornithopter Chassis Mk5', FALSE),
('Assault Ornithopter Chassis Mk6', FALSE),
('Assault Ornithopter Engine Mk5', FALSE),
('Assault Ornithopter Engine Mk6', FALSE),
('Assault Ornithopter Generator Mk5', FALSE),
('Assault Ornithopter Generator Mk6', FALSE),
('Assault Ornithopter Cabin Mk5', FALSE),
('Assault Ornithopter Cabin Mk6', FALSE),
('Assault Ornithopter Tail Mk5', FALSE),
('Assault Ornithopter Tail Mk6', FALSE),
('Assault Ornithopter Cockpit Mk5', FALSE),
('Assault Ornithopter Cockpit Mk6', FALSE),
('Assault Ornithopter Storage Mk5', FALSE),
('Assault Ornithopter Rocket Launcher Mk5', FALSE),
('Assault Ornithopter Rocket Launcher Mk6', FALSE),
('Assault Ornithopter Wing Mk5', FALSE),
('Assault Ornithopter Wing Mk6', FALSE),
('Hummingbird Wing Module Mk5', FALSE),
('Hummingbird Wing Module Mk6', FALSE),
('Carrier Ornithopter Thruster Mk6', FALSE),
('Steady Carrier Boost Module Mk6', FALSE),
('Carrier Ornithopter Chassis Mk6', FALSE),
('Carrier Ornithopter Engine Mk6', FALSE),
('Carrier Ornithopter Generator Mk6', FALSE),
('Carrier Ornithopter Main Hull Mk6', FALSE),
('Carrier Ornithopter Tail Hull Mk6', FALSE),
('Carrier Ornithopter Side Hull Mk6', FALSE),
('Carrier Ornithopter Wing Mk6', FALSE),
('Roc Carrier Wing', FALSE),
('Sandbike Booster Mk2', FALSE),
('Sandbike Booster Mk3', FALSE),
('Sandbike Booster Mk4', FALSE),
('Sandbike Booster Mk5', FALSE),
('Sandbike Booster Mk6', FALSE),
('Night Rider Sandbike Boost Mk2', FALSE),
('Night Rider Sandbike Boost Mk3', FALSE),
('Night Rider Sandbike Boost Mk4', FALSE),
('Night Rider Sandbike Boost Mk5', FALSE),
('Night Rider Sandbike Boost Mk6', FALSE),
('Sandbike Chassis Mk1', FALSE),
('Sandbike Chassis Mk2', FALSE),
('Sandbike Chassis Mk3', FALSE),
('Sandbike Chassis Mk4', FALSE),
('Sandbike Chassis Mk5', FALSE),
('Sandbike Chassis Mk6', FALSE),
('Sandbike Engine Mk1', FALSE),
('Sandbike Engine Mk2', FALSE),
('Sandbike Engine Mk3', FALSE),
('Sandbike Engine Mk4', FALSE),
('Sandbike Engine Mk5', FALSE),
('Sandbike Engine Mk6', FALSE),
('Mohandis Sandbike Engine Mk1', FALSE),
('Mohandis Sandbike Engine Mk2', FALSE),
('Mohandis Sandbike Engine Mk3', FALSE),
('Mohandis Sandbike Engine Mk4', FALSE),
('Mohandis Sandbike Engine Mk5', FALSE),
('Mohandis Sandbike Engine Mk6', FALSE),
('Sandbike PSU Mk1', FALSE),
('Sandbike PSU Mk2', FALSE),
('Sandbike PSU Mk3', FALSE),
('Sandbike PSU Mk4', FALSE),
('Sandbike PSU Mk5', FALSE),
('Sandbike PSU Mk6', FALSE),
('Sandbike Hull Mk1', FALSE),
('Sandbike Hull Mk2', FALSE),
('Sandbike Hull Mk3', FALSE),
('Sandbike Hull Mk4', FALSE),
('Sandbike Hull Mk5', FALSE),
('Sandbike Hull Mk6', FALSE),
('Sandbike Inventory Mk1', FALSE),
('Sandbike Inventory Mk2', FALSE),
('Sandbike Tread Mk1', FALSE),
('Sandbike Tread Mk2', FALSE),
('Sandbike Tread Mk3', FALSE),
('Sandbike Tread Mk4', FALSE),
('Sandbike Tread Mk5', FALSE),
('Sandbike Tread Mk6', FALSE),
('Sandbike Scanner Mk2', FALSE),
('Sandbike Backseat Mk1', FALSE),
('Sandcrawler Chassis Mk6', FALSE),
('Sandcrawler Engine Mk6', FALSE),
('Walker Sandcrawler Engine Mk6', FALSE),
('Sandcrawler PSU Mk6', FALSE),
('Sandcrawler Cabin Mk6', FALSE),
('Sandcrawler Tread Mk6', FALSE),
('Dampened Sandcrawler Treads', FALSE),
('Sandcrawler Centrifuge Mk6', FALSE),
('Upgraded Regis Spice Container', FALSE),
('Sandcrawler Vacuum Mk6', FALSE),
('Treadwheel Chassis Mk4', FALSE),
('Treadwheel Chassis Mk5', FALSE),
('Treadwheel Chassis Mk6', FALSE),
('Treadwheel PSU Mk4', FALSE),
('Treadwheel PSU Mk5', FALSE),
('Treadwheel PSU Mk6', FALSE),
('Treadwheel Engine Mk4', FALSE),
('Treadwheel Engine Mk5', FALSE),
('Treadwheel Engine Mk6', FALSE),
('Treadwheel Tread Mk4', FALSE),
('Treadwheel Tread Mk5', FALSE),
('Treadwheel Tread Mk6', FALSE),
('Treadwheel Hull Mk4', FALSE),
('Treadwheel Hull Mk5', FALSE),
('Treadwheel Hull Mk6', FALSE),
('Treadwheel Passenger Mk1', FALSE),
('Treadwheel Boost Mk4', FALSE),
('Treadwheel Boost Mk5', FALSE),
('Treadwheel Boost Mk6', FALSE),
('Treadwheel Inventory Mk2', FALSE),
('Treadwheel Scanner Mk2', FALSE),
('Steady Treadwheel Boost Module Mk4', FALSE),
('Swift Treadwheel Engine Mk4', FALSE),
('Steady Treadwheel Boost Module Mk5', FALSE),
('Swift Treadwheel Engine Mk5', FALSE),
('Steady Treadwheel Boost Module Mk6', FALSE),
('Swift Treadwheel Engine Mk6', FALSE),
('Carrier Ornithopter Cargo Container', FALSE),
('Vehicle Backup Tool', FALSE),
('Replica Pulse-sword', FALSE),
('Jolt-sword', FALSE),
('Spark-sword', FALSE),
('Shock-sword ', FALSE),
('Pseudo Pulse-Sword', FALSE),
('Sardaukar Intimidator', FALSE),
('Piter''s Disruptor', FALSE),
('Abulurd''s Rapture', FALSE),
('Way of the Misr', FALSE),
('Way of the Desert', FALSE),
('Way of the Fighter', FALSE),
('Way of the Lost', FALSE),
('Way of the Wanderer', FALSE),
('Way of the Fallen ', FALSE),
('Shishakli''s Bite', FALSE),
('Taqwa''s Double', FALSE),
('Shadrath''s Edge', FALSE),
('Perforator', FALSE),
('Syndicate Impaler', FALSE),
('Eviscerator', FALSE),
('Ripper', FALSE),
('Shredder', FALSE),
('Shellburster', FALSE),
('Starburst', FALSE),
('Firestorm', FALSE),
('Static Needle', FALSE),
('Halleck''s Pick', FALSE),
('Kharet Viper', FALSE),
('Poison Mist', FALSE),
('Vaporizer', FALSE),
('Shaitan''s Tongue', FALSE),
('Cauterizer', FALSE),
('Moisture Sealer', FALSE),
('Denira''s Gift', FALSE),
('Searing Shiv', FALSE),
('Salusan Vengeance', FALSE),
('Scrubber', FALSE),
('Pipecleaner', FALSE),
('The Tapper', FALSE),
('Indara''s Lullaby', FALSE),
('Mendek''s Rattle', FALSE),
('Stammershot', FALSE),
('Zaal''s Companion', FALSE),
('Fila''s Regret', FALSE),
('Aren''s Vengeance', FALSE),
('Survey Probe Launcher', FALSE),
('Survey Probe', FALSE),
('Omni Static Compactor', FALSE),
('Compact Compactor Mk6', FALSE),
('Compact Compactor Mk5', FALSE),
('Compact Compactor Mk4', FALSE),
('Compact Compactor Mk3', FALSE),
('Staking Unit', FALSE),
('Regis Drillshot FK7', FALSE),
('Vertical Staking Unit', FALSE),
('Adept Drillshot FK7', FALSE),
('House Drillshot FK7', FALSE),
('Regis JABAL Spitdart', FALSE),
('Adept JABAL Spitdart', FALSE),
('House JABAL Spitdart', FALSE),
('Artisan JABAL Spitdart', FALSE),
('A Dart for Every Man', FALSE),
('Relentless', FALSE),
('Ironwatch Special', FALSE),
('Seb''s Kisser', FALSE),
('Legion Tattoo', FALSE),
('Regis Burst Drillshot', FALSE),
('Adept Burst Drillshot', FALSE),
('House Burst Drillshot', FALSE),
('Penetrator', FALSE),
('Scrap Metal Knife', FALSE),
('Regis GRDA 44', FALSE),
('Adept GRDA 44', FALSE),
('House GRDA 44', FALSE),
('Artisan GRDA 44', FALSE),
('Standard GRDA 44 ', FALSE),
('Handheld Life Scanner Mk3', FALSE),
('Long Range Scanner', FALSE),
('Handheld Resource Scanner', FALSE),
('The Ancient Way', FALSE),
('Regis Missile Launcher', FALSE),
('Rocket', FALSE),
('Welding Torch Mk5', FALSE),
('Welding Torch Mk3', FALSE),
('Welding Torch Mk1', FALSE),
('Regis Rapier', FALSE),
('Adept Rapier', FALSE),
('House Rapier', FALSE),
('Incendiary Gel', FALSE),
('Kynes''s Cutteray', FALSE),
('Tarl Cutteray', FALSE),
('Sandflies Carver', FALSE),
('Callie''s Breaker', FALSE),
('Cutteray Mk3', FALSE),
('Cutteray Mk5', FALSE),
('Cutteray Mk4', FALSE),
('Cutteray Mk6', FALSE),
('Olef''s Quickcutter', FALSE),
('Sim''s Cutter', FALSE),
('Improvised Cutteray', FALSE),
('Cutteray Mk2', FALSE),
('Cutteray Mk1', FALSE),
('Dunewatcher', FALSE),
('Thufir''s Best', FALSE),
('Long Shot', FALSE),
('Assassin''s Rifle', FALSE),
('Regis Tripleshot Repeating Rifle', FALSE),
('Fivefinger''s Tripleshot Rifle', FALSE),
('Bashar''s Command', FALSE),
('Extravagant Message', FALSE),
('Experimental Vulcan GAU-94', FALSE),
('Plasma Cannon', FALSE),
('Replica Pulse-knife', FALSE),
('Jolt-knife', FALSE),
('Spark-Knife', FALSE),
('Shock-Knife', FALSE),
('Feyd''s Drinker', FALSE),
('Pardot''s Drinker', FALSE),
('Shadrath''s Drinker', FALSE),
('Glutton''s Drinker', FALSE),
('Scipio''s Drinker', FALSE),
('Kaleff''s Drinker', FALSE),
('Regis Kindjal', FALSE),
('Adept Kindjal', FALSE),
('House Kindjal', FALSE),
('Artisan Kindjal', FALSE),
('Standard Kindjal', FALSE),
('Kindjal', FALSE),
('Missile', FALSE),
('Seethe', FALSE),
('Cope', FALSE),
('Regis Disruptor Pistol', FALSE),
('Adept Disruptor Pistol', FALSE),
('House Disruptor Pistol', FALSE),
('Artisan Disruptor Pistol', FALSE),
('Heavy Darts', FALSE),
('Regis Rafiq Snubnose', FALSE),
('Adept Rafiq Snubnose', FALSE),
('House Rafiq Snubnose', FALSE),
('Artisan Rafiq Snubnose', FALSE),
('Regis Karpov 38', FALSE),
('Adept Karpov 38', FALSE),
('House Karpov 38', FALSE),
('Artisan Karpov 38', FALSE),
('Standard Karpov 38', FALSE),
('Karpov 38', FALSE),
('Glowtube', FALSE),
('Glasser', FALSE),
('Scorchbolt', FALSE),
('Regis Dirk', FALSE),
('Adept Dirk', FALSE),
('House Dirk', FALSE),
('Artisan Dirk', FALSE),
('Buoyant Reaper Mk6', FALSE),
('Buoyant Reaper Mk5', FALSE),
('Buoyant Reaper Mk4', FALSE),
('Buoyant Reaper Mk3', FALSE),
('Buoyant Reaper Mk2', FALSE),
('Dew Scythe Mk4', FALSE),
('Dew Reaper Mk2', FALSE),
('Omni Focused Dew Scythe', FALSE),
('Focused Reaper Mk5', FALSE),
('Dew Scythe Mk6', FALSE),
('Collapsible Dew Reaper Mk6', FALSE),
('Collapsible Dew Reaper Mk5', FALSE),
('Collapsible Dew Reaper Mk4', FALSE),
('Dew Reaper Mk6', FALSE),
('Dew Reaper Mk4', FALSE),
('Regis Sword', FALSE),
('Adept Sword', FALSE),
('House Sword', FALSE),
('Artisan Sword', FALSE),
('Standard Sword', FALSE),
('Regis Maula Pistol', FALSE),
('Adept Maula Pistol', FALSE),
('House Maula Pistol', FALSE),
('Artisan Maula Pistol', FALSE),
('Standard Maula Pistol', FALSE),
('Maula Pistol', FALSE),
('Improvised Maula Pistol', FALSE),
('Black Market K-28 Lasgun', FALSE),
('Arhun K-28 Lasgun', FALSE),
('Industrial Static Compactor', FALSE),
('Static Compactor', FALSE),
('Filter Extractor Mk6', FALSE),
('Filter Extractor Mk5', FALSE),
('Filter Extractor Mk4', FALSE),
('Filter Extractor Mk3', FALSE),
('Impure Extractor Mk6', FALSE),
('Impure Extractor Mk5', FALSE),
('Blood Extractor Mk6', FALSE),
('Blood Extractor Mk4', FALSE),
('Blood Extractor Mk2', FALSE),
('Improvised Blood Extractor', FALSE),
('Binoculars', FALSE),
('Construction Tool', FALSE),
('Regis Disruptor M11', FALSE),
('Adept Disruptor M11', FALSE),
('House Disruptor M11', FALSE),
('Artisan Disruptor M11', FALSE),
('Standard Disruptor M11', FALSE),
('Regis Vulcan GAU-92', FALSE),
('Adept Vulcan GAU-92', FALSE),
('House Vulcan GAU-92', FALSE),
('Atreides LMG', FALSE),
('Light Darts', FALSE),
('The Glutton''s Hook', FALSE),
('Ari''s Pistol', FALSE),
('Feyd''s Take-Down Blade', FALSE),
('Zantara''s Crysknife', FALSE),
('Unfixed Crysknife', FALSE),
('Water Shipper''s Dew Reaper', FALSE),
('Ambition', FALSE),
('Sword of Seven Sorrows', FALSE),
('Bite Back Blade', FALSE),
('Spike Hilt Sword', FALSE),
('Duraluminum Pyrocket', FALSE),
('Plastanium Pyrocket', FALSE),
('Adept Missile Launcher', FALSE),
('Experimental Lightning Gun', FALSE),
('Adept Dual Blades', FALSE),
('Regis Dual Blades', FALSE),
('Asterion�s End', FALSE),
('Feyd�s Spare Blades', FALSE),
('Burning Blades', FALSE),
('Personal Light', FALSE),
('Accelerator Power Pack', FALSE),
('Improvised Power Pack', FALSE),
('Power Pack Mk2', FALSE),
('Power Pack Mk4', FALSE),
('Power Pack Mk6', FALSE),
('Power Pack Mk1', FALSE),
('Power Pack Mk3', FALSE),
('Power Pack Mk5', FALSE),
('Sentinel Belt', FALSE),
('Old Sparky Mk1', FALSE),
('Old Sparky Mk2', FALSE),
('Old Sparky Mk3', FALSE),
('Old Sparky Mk4', FALSE),
('Young Sparky Mk5', FALSE),
('Young Sparky Mk6', FALSE),
('Holtzman Shield Mk2', FALSE),
('Holtzman Shield Mk3', FALSE),
('Holtzman Shield Mk5', FALSE),
('Adaptive Holtzman Shield', FALSE),
('Paranoid''s Holtzman Shield', FALSE),
('The Emperor''s Wings Mk1', FALSE),
('The Emperor''s Wings Mk2', FALSE),
('The Emperor''s Wings Mk3', FALSE),
('The Emperor''s Wings Mk4', FALSE),
('The Emperor''s Wings Mk5', FALSE),
('The Emperor''s Wings Mk6', FALSE),
('Leap Suspensor Belt', FALSE),
('Full Suspensor Belt', FALSE),
('Planar Suspensor Belt', FALSE),
('Responsive Planar Suspensor Belt', FALSE),
('Passive Suspensor Belt', FALSE),
('Elohim-Class Suspensor Belt', FALSE),
('Electrical Wind Turbine component', FALSE),
('Solido Replicator', FALSE),
('Base Reconstruction Tool', FALSE),
('Fuel Cell', FALSE),
('Desert Eye Sniper Rifle', FALSE),
('Clone Cleaver', FALSE),
('Dragon''s Breath Flamethrower', FALSE),
('The Sword of Seven Sorrows', FALSE),
('Dune Man Coverall Hood', FALSE),
('Dune Man Coverall Jacket', FALSE),
('Dune Man Coverall Gloves', FALSE),
('Dune Man Coverall Pants', FALSE),
('Dune Man Coverall Boots', FALSE),
('Atreides Envoy Maula Pistol Variant', FALSE),
('Atreides Envoy  Karpov Rifle Variant', FALSE),
('Atreides Envoy Spitdart Variant', FALSE),
('Atreides Envoy Drillshot Variant', FALSE),
('Atreides Envoy Lasgun Variant', FALSE),
('Atreides Envoy Sword Variant', FALSE),
('Atreides Envoy Heavy Armor Jacket Variant', FALSE),
('Atreides Envoy Light Armor Jacket Variant', FALSE),
('Atreides Sandcrawler Variant', FALSE),
('Atreides Carrier Ornithopter Variant', FALSE),
('Harkonnen Enforcer Maula Pistol Variant', FALSE),
('Harkonnen Enforcer Spitdart Variant', FALSE),
('Harkonnen Enforcer Drillshot Variant', FALSE),
('Harkonnen Enforcer Lasgun Variant', FALSE),
('Harkonnen Enforcer Sword Variant', FALSE),
('Harkonnen Enforcer Heavy Armor Jacket Variant', FALSE),
('Harkonnen Enforcer Light Armor Jacket Variant', FALSE),
('Harkonnen Sandcrawler Variant', FALSE),
('Harkonnen Carrier Ornithopter Variant', FALSE),
('Atreides Envoy Ornithopter Variant', FALSE),
('Harkonnen Enforcer Scout Ornitopther Variant', FALSE),
('Harkonnen Buildables Swatch', FALSE),
('Atreides Buildables Swatch', FALSE),
('Contraband Sandbike Variant', FALSE),
('Contraband Buggy Variant', FALSE),
('Contraband Assault Ornithopter Variant', FALSE),
('Contraband Scout Ornithopter Variant', FALSE),
('Contraband Carrier Ornithopter Variant', FALSE),
('Contraband Light Armor Jacket Variant', FALSE),
('Contraband Drillshot Variant', FALSE),
('Contraband Snubnose Variant', FALSE),
('Contraband Heavy Armor Jacket Variant', FALSE),
('Contraband Pyrocket Variant', FALSE),
('Contraband Sandcrawler Variant', FALSE),
('House Alexin Placeables Swatch', FALSE),
('House Argosaz Placeables Swatch', FALSE),
('House Dyvetz Placeables Swatch', FALSE),
('House Ecaz Placeables Swatch', FALSE),
('House Hagal Placeabless Swatch', FALSE),
('House Hurata Placeables Swatch', FALSE),
('House Imota Placeables Swatch', FALSE),
('House Kenola Placeables Swatch', FALSE),
('House Lindaren Placeables Swatch', FALSE),
('House Maros Placeables Swatch', FALSE),
('House Mikarrol Placeables Swatch', FALSE),
('House Moritani Placeables Swatch', FALSE),
('House Mutelli Placeables Swatch', FALSE),
('House Novebruns Placeables Swatch', FALSE),
('House Richese Placeables Swatch', FALSE),
('House Sor Placeables Swatch', FALSE),
('House Spinnette Placeables Swatch', FALSE),
('House Taligari Placeables Swatch', FALSE),
('House Thorvald Placeables Swatch', FALSE),
('House Tseida Placeables Swatch', FALSE),
('House Varota Placeables Swatch', FALSE),
('House Vernius Placeables swatch', FALSE),
('House Wallach Placeables Swatch', FALSE),
('House Wayku Placeables Swatch', FALSE),
('House Wydras Placeables Swatch', FALSE),
('''Thopter Pilot Set', FALSE),
('Habiliments of the Hidden Hand', FALSE),
('Spice Worker�s Garb', FALSE),
('Atreides Envoy Sandbike Variant', FALSE),
('Harkonnen Enforcer Sandbike Variant', FALSE),
('Atreides Envoy Buggy Variant', FALSE),
('Harkonnen Enforcer Buggy Variant', FALSE),
('Harkonnen Enforcer Karpov', FALSE),
('Atreides Rusher Armor Set', FALSE),
('Harkonnen Rusher Armor Set ', FALSE),
('Contraband Swatch', FALSE),
('Precision Barrel Adjuster', FALSE),
('Concussive Dampening', FALSE),
('Energy Resistant Weave', FALSE),
('Detoxifying Fabrics', FALSE),
('Dart-proof Latticing', FALSE),
('Flame-resistant Fabrics', FALSE),
('Blade-warding Weave', FALSE),
('Radiation Absorbing Fabrics', FALSE),
('Radiation Shielded Latticing', FALSE),
('Concussive Redirection', FALSE),
('Penetrative Reinforcement', FALSE),
('Energy Dispersing Padding', FALSE),
('Garment Reinforcement', FALSE),
('Desert-tested Weave', FALSE),
('Curative-infused Padding', FALSE),
('Karpov 38 Pressurizer', FALSE),
('Karpov 38 Dart Sprayer', FALSE),
('Karpov 38 Heavy Kit', FALSE),
('Karpov 38 Focuser', FALSE),
('Karpov 38 Precision Kit', FALSE),
('Heavy Caliber Upgrade', FALSE),
('Protective Coating', FALSE),
('Pyrocket Supercharger', FALSE),
('Pyrocket Quickloader', FALSE),
('Flamethrower Amplifier', FALSE),
('Flamethrower Superheater', FALSE),
('Flamethrower Nozzle Extension', FALSE),
('Flamethrower Quickloader', FALSE),
('Tactical Enhancer', FALSE),
('Rafiq Snubnose Heavy Kit', FALSE),
('Rafiq Snubnose Disruptive Coating', FALSE),
('Rafiq Snubnose Quickdraw Assembly', FALSE),
('Rafiq Snubnose Expander', FALSE),
('Rafiq Snubnose Sprayer', FALSE),
('Lasgun Focuser', FALSE),
('Lasgun Extender', FALSE),
('Lasgun Harmonizer', FALSE),
('Lasgun Amplifier', FALSE),
('VULCAN GAU-92 Expander', FALSE),
('VULCAN GAU-92 Focuser', FALSE),
('VULCAN GAU-92 Disruptive Coating', FALSE),
('VULCAN GAU-92 Sprayer', FALSE),
('Capacity Expander', FALSE),
('Maula Pistol Sprayer', FALSE),
('Maula Pistol Disruptive Coating', FALSE),
('Maula Pistol Expander', FALSE),
('Maula Pistol Barrel Extender', FALSE),
('Maula Pistol Tactical Enhancer', FALSE),
('Blade Sharpener', FALSE),
('Blade Grip Adjuster', FALSE),
('Blade Flexi-Coating', FALSE),
('Aggressive Grip Adjuster', FALSE),
('Lightweight Adjuster', FALSE),
('Heavy Blade Adjuster', FALSE),
('Defensive Grip Adjuster', FALSE),
('Blade Optimizer', FALSE),
('Edge Optimizer', FALSE),
('Barrel Extender', FALSE),
('Quick-release Trigger', FALSE),
('Recoil Adjuster', FALSE),
('Quickloader', FALSE),
('Missile Launcher Fragmenter', FALSE),
('Missile Launcher Disruptive Coating', FALSE),
('Missile Launcher Quickloader', FALSE),
('Missile Launcher Heavy Payload', FALSE),
('GRDA 44 Tactical Amplifier', FALSE),
('GRDA 44 Expander', FALSE),
('GRDA 44 Amplifier', FALSE),
('GRDA 44 Optimizer', FALSE),
('GRDA 44 Sprayer', FALSE),
('GRDA 44 Micro-Rigidity Coating', FALSE),
('Disruptive Coating', FALSE),
('Drillshot FK7 Tactical Adjuster', FALSE),
('Drillshot FK7 Amplifier', FALSE),
('Drillshot FK7 Optimizer', FALSE),
('Drillshot FK7 Sprayer', FALSE),
('Drillshot FK7 Quickloader', FALSE),
('Disruptor M11 Precision Tuning', FALSE),
('Disruptor M11 Quickloader', FALSE),
('Disruptor M11 Shield Breaker', FALSE),
('Disruptor M11 Sprayer', FALSE),
('Disruptor M11 Amplifier', FALSE),
('Disruptor M11 Heavy Kit', FALSE),
('JABAL Spitdart Tactical Enhancer', FALSE),
('JABAL Spitdart Range Adjuster', FALSE),
('JABAL Spitdart Amplifier', FALSE),
('JABAL Spitdart Disruptive Coating', FALSE),
('JABAL Spitdart Expander', FALSE),
('JABAL Spitdart Toxicity Amplifier', FALSE),
('Woven Reinforcement', FALSE),
('Water', FALSE);
